# Generated by Django 5.2 on 2025-04-18 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='jobseeker', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
