# Generated by Django 5.2 on 2025-04-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_employer_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='employer',
        ),
        migrations.AddField(
            model_name='employer',
            name='company',
            field=models.CharField(default='Summit Group', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='location',
            field=models.CharField(default='Dhaka', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
