# Generated by Django 5.2 on 2025-07-01 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_jobseeker_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='about',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='experiences',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
