# Generated by Django 5.2 on 2025-07-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_jobseeker_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='website',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='current_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
