# Generated by Django 5.2 on 2025-04-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_detail_min_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
