# Generated by Django 5.2 on 2025-04-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_detail_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='locations',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
