# Generated by Django 5.2 on 2025-04-21 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_detail_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='education',
            field=models.CharField(choices=[('J.S.C', 'J.S.C'), ('S.S.C', 'S.S.C'), ('H.S.C', 'H.S.C'), ('Master', 'Master')], default='J.S.C', max_length=10),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)]),
        ),
    ]
