# Generated by Django 5.2 on 2025-04-21 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_requirement_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='jobs.job'),
        ),
    ]
