# Generated by Django 5.2 on 2025-04-26 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply_review', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='job_seeker',
            new_name='jobseeker',
        ),
    ]
