# Generated by Django 5.2 on 2025-04-26 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_review', '0004_rename_job_seeker_application_jobseeker'),
        ('jobs', '0007_alter_requirement_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job', unique=True),
        ),
    ]
