# Generated by Django 5.2 on 2025-04-26 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_review', '0005_alter_application_job'),
        ('jobs', '0007_alter_requirement_job'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'jobseeker')},
        ),
    ]
